//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public string idAdmission { get; set; }
        public Nullable<bool> surgery { get; set; }
        public Nullable<System.DateTime> dateAdmission { get; set; }
        public Nullable<System.DateTime> dateSurgery { get; set; }
        public Nullable<System.DateTime> dateLeave { get; set; }
        public Nullable<bool> television { get; set; }
        public Nullable<bool> telephone { get; set; }
        public string NSS { get; set; }
        public int numeroLit { get; set; }
        public string idMedecin { get; set; }
    
        public virtual Bed Bed { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
